version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://****:****@db:5432/yarn?sslmode=disable
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=****
      - POSTGRES_PASSWORD=****
      - POSTGRES_DB=****
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
